name: braided_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - ansi2html=1.9.2
  - anyio=3.7.1
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.1
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dash=2.13.0
  - dask=2024.2.1
  - dask-core=2024.2.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2024.2.1
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - flask=3.1.2
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - fsspec=2025.10.0
  - gdal=3.11.4
  - gdk-pixbuf=2.44.4
  - geos=3.14.0
  - glib=2.86.2
  - glib-tools=2.86.2
  - glslang=15.4.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imath=3.2.2
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2025.3.0
  - ipykernel=7.1.0
  - ipympl=0.9.7
  - ipython=8.21.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - itsdangerous=2.2.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter=1.0.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_server=1.24.0
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libasprintf=0.22.5
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcurl=8.17.0
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.11.4
  - libgettextpo=0.22.5
  - libglib=2.86.2
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libogg=1.3.5
  - libopencv=4.12.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libparquet=22.0.0
  - libpng=1.6.51
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libusb=1.0.29
  - libutf8proc=2.11.2
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.9
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - mistune=3.1.4
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.12.0
  - nbclassic=1.3.3
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4
  - notebook=6.5.4
  - notebook-shim=0.2.4
  - numpy=1.24.2
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.4.2
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.25.3
  - openpyxl=3.1.5
  - openssl=3.6.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=1.5.3
  - pandoc=3.8.2.1
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.2
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.5.0
  - ply=3.11
  - proj=9.6.2
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pugixml=1.15
  - pure_eval=0.2.3
  - py-opencv=4.12.0
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pyarrow-hotfix=0.7
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qt-main=5.15.15
  - qt6-main=6.9.3
  - qtconsole-base=5.7.0
  - qtpy=2.4.3
  - rav1e=0.7.1
  - re2=2025.11.05
  - referencing=0.37.0
  - requests=2.32.5
  - retrying=1.4.2
  - rpds-py=0.29.0
  - scikit-learn=1.2.2
  - scipy=1.9.3
  - sdl2=2.32.56
  - sdl3=3.2.26
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shaderc=2025.3
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - spirv-tools=2025.4
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tabulate=0.9.0
  - tbb=2021.13.0
  - tblib=3.2.2
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - toolz=1.1.0
  - torchinfo=1.8.0
  - tornado=6.5.2
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - x264=1!164.3095
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
    - sympy==1.13.1
    - torchaudio==2.5.1
    - torchvision==0.20.1